/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Popover: typeof import('./src/components/Popover.vue')['default']
    RiArrowLeftSLine: typeof import('~icons/ri/arrow-left-s-line')['default']
    RiArrowRightSLine: typeof import('~icons/ri/arrow-right-s-line')['default']
    RiTimeLine: typeof import('~icons/ri/time-line')['default']
    TimePicker: typeof import('./src/components/TimePicker.vue')['default']
  }
}
